"""loan_product_methods

Revision ID: 3c50664e71df
Revises: 40396dcafe09
Create Date: 2026-07-10 08:25:32.586071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c50664e71df'
down_revision: Union[str, Sequence[str], None] = '40396dcafe09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_products', sa.Column('interest_method', sa.String(), nullable=False))
    op.add_column('loan_products', sa.Column('repayment_frequency', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan_products', 'repayment_frequency')
    op.drop_column('loan_products', 'interest_method')
    # ### end Alembic commands ###
