"""repayments_and_loan_ledger

Revision ID: 40396dcafe09
Revises: 5aa1857ee456
Create Date: 2026-07-10 08:19:06.433735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40396dcafe09'
down_revision: Union[str, Sequence[str], None] = '5aa1857ee456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_transactions',
    sa.Column('loan_id', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('interest_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('penalty_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repayments',
    sa.Column('loan_id', sa.String(), nullable=False),
    sa.Column('schedule_id', sa.String(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('principal_paid', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('interest_paid', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('penalty_paid', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_paid', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reference_no', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('received_by', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['loan_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repayments')
    op.drop_table('loan_transactions')
    # ### end Alembic commands ###
