"""loan_engine_phase1

Revision ID: 5aa1857ee456
Revises: 4ef619be2be0
Create Date: 2026-07-10 08:16:46.662576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aa1857ee456'
down_revision: Union[str, Sequence[str], None] = '4ef619be2be0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_products',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('max_term_months', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loans',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('branch_id', sa.String(), nullable=True),
    sa.Column('borrower_id', sa.String(), nullable=False),
    sa.Column('loan_product_id', sa.String(), nullable=False),
    sa.Column('loan_number', sa.String(), nullable=False),
    sa.Column('principal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('term_months', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('disbursement_date', sa.Date(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrowers.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['loan_product_id'], ['loan_products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_number')
    )
    op.create_table('loan_schedules',
    sa.Column('loan_id', sa.String(), nullable=False),
    sa.Column('installment_no', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('principal_due', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('interest_due', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_due', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan_schedules')
    op.drop_table('loans')
    op.drop_table('loan_products')
    # ### end Alembic commands ###
