"""add branch active status

Revision ID: 716ba8bc5edd
Revises: a13e7effc0d1
Create Date: 2026-09-07 09:08:32.351220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '716ba8bc5edd'
down_revision: Union[str, Sequence[str], None] = 'a13e7effc0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branches', 'is_active')
    # ### end Alembic commands ###
