"""add branch tenant uniqueness

Revision ID: a13e7effc0d1
Revises: a9b3e55ce3d4
Create Date: 2026-09-07 09:01:35.762410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a13e7effc0d1'
down_revision: Union[str, Sequence[str], None] = 'a9b3e55ce3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_branches_tenant_code', 'branches', ['tenant_id', 'code'])
    op.create_unique_constraint('uq_branches_tenant_name', 'branches', ['tenant_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_branches_tenant_name', 'branches', type_='unique')
    op.drop_constraint('uq_branches_tenant_code', 'branches', type_='unique')
    # ### end Alembic commands ###
