"""borrower_types

Revision ID: ac73986489e4
Revises: 0a03fcfbcc82
Create Date: 2026-07-10 08:36:27.642718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac73986489e4'
down_revision: Union[str, Sequence[str], None] = '0a03fcfbcc82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrowers', sa.Column('borrower_type', sa.String(), nullable=False))
    op.add_column('borrowers', sa.Column('business_name', sa.String(), nullable=True))
    op.alter_column('borrowers', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('borrowers', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('borrowers', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('borrowers', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('borrowers', 'business_name')
    op.drop_column('borrowers', 'borrower_type')
    # ### end Alembic commands ###
